import { useState, useEffect, useMemo } from "react";
import type { SurfaceProps, RecordRow, TaskRow, MarketplaceData, MarketplaceItem } from "./surfaceContracts";
import type { ProjectSummary } from "@shared/workspace";
import { fetchJson, fetchEvidence, jsonRequest } from "./api";
import { Search, Cloud } from "lucide-react";
import { EmptyState, StatusBadge, EvidenceRows, EvidenceCards, TaskTable } from "./ui";
import { viewLabel } from "./navigation";

function OnlineSurface({ view, project, onInspectorContext }: SurfaceProps) {
  const [market, setMarket] = useState<MarketplaceData>({}); const [control, setControl] = useState<RecordRow | null>(null); const [tasks, setTasks] = useState<TaskRow[]>([]); const [selectedId, setSelectedId] = useState(""); const [query, setQuery] = useState(""); const [message, setMessage] = useState("Loading Online evidence…"); const [operation, setOperation] = useState<RecordRow | null>(null);
  const refresh = async () => { try { const [m, c, t] = await Promise.all([fetchJson<MarketplaceData>(project ? `/api/workspace/projects/${encodeURIComponent(project.id)}/marketplace` : "/api/workspace/marketplace"), fetchJson<RecordRow>("/api/workspace/online/control-center"), fetchJson<{ tasks: TaskRow[] }>("/api/workspace/tasks")]); setMarket(m); setControl(c); setTasks(t.tasks || []); if (!selectedId && m.items?.[0]) setSelectedId(m.items[0].id); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Online evidence failed."); } };
  useEffect(() => { void refresh(); }, [project?.id]);
  const items = useMemo(() => { let list = market.items || []; if (view === "extensions") list = list.filter((item) => item.taxonomy?.includes("extensions")); if (view === "models") list = list.filter((item) => item.category === "models"); if (view === "agents") list = list.filter((item) => item.category === "agents"); if (view === "tools") list = list.filter((item) => item.category === "tools"); if (view === "integrations") list = list.filter((item) => item.taxonomy?.includes("integrations")); if (view === "installed") list = list.filter((item) => item.installed); if (view === "updates") list = list.filter((item) => item.updateState?.state === "VERIFIED" && /UPDATE_AVAILABLE/i.test(item.updateState.value || "")); if (view === "security") list = list.filter((item) => item.trust !== "TRUSTED" || (item.permissions || []).some((permission) => permission.required) || ["REMOTE_REGISTRY", "CACHED_REMOTE"].includes(item.authority?.kind || "")); return list.filter((item) => `${item.name} ${item.description || ""} ${item.source || ""} ${(item.capabilities || []).join(" ")}`.toLowerCase().includes(query.toLowerCase())); }, [market, view, query]);
  const selected = (market.items || []).find((item) => item.id === selectedId) || items[0];
  const selectItem = (item: MarketplaceItem) => {
    setSelectedId(item.id);
    setOperation(null);
    onInspectorContext?.({ kind: "online-item", item, title: item.name, view, compatibility: project ? item.projectCompatibility?.state : "NOT_EVALUATED", projectName: project?.name });
  };
  if (view === "providers" || view === "remote-sources") { const rows = view === "providers" ? [...(market.providers || []), ...(market.adapters || [])] : (market.adapters || []).filter((row) => row.kind === "remote"); return <section className="kw-online"><OnlineContext project={project} control={control} /><div className="kw-toolbar"><h2>{viewLabel("online", view)}</h2><button onClick={() => void refresh()}>Refresh evidence</button></div><EvidenceCards rows={rows} /></section>; }
  if (view === "downloads" || view === "activity") { const list = tasks.filter((task) => view === "downloads" ? /download|pull|install|update/i.test(JSON.stringify(task)) : /online|marketplace|download|install|update|provider/i.test(JSON.stringify(task))); return <section className="kw-online"><OnlineContext project={project} control={control} /><TaskTable tasks={list} /></section>; }
  const operate = async (kind: "install" | "health" | "run" | "update" | "uninstall") => { if (!selected) return; const destructive = ["install", "run", "update", "uninstall"].includes(kind); if (destructive && !window.confirm(`${kind} ${selected.name}? Review the displayed authority, integrity, permissions and trust evidence first.`)) return; setOperation({ state: "RUNNING", operation: kind }); try { const url = `/api/workspace/marketplace/items/${encodeURIComponent(selected.id)}/${kind}`; const result = kind === "health" ? await fetchEvidence(url) : await fetchEvidence(url, jsonRequest({ confirmed: true })); setOperation({ operation: kind, status: result.status, ...result.data }); await refresh(); } catch (error) { setOperation({ operation: kind, state: "FAILED", error: error instanceof Error ? error.message : "Operation failed" }); } };
  return <section className="kw-online"><OnlineContext project={project} control={control} /><div className="kw-online-toolbar"><label><Search size={14} /><input aria-label="Search Online catalog" value={query} onChange={(e) => setQuery(e.target.value)} /></label><span>{items.length} result(s)</span><button onClick={() => void refresh()}>Refresh local evidence</button></div>{message && <p className="kw-message">{message}</p>}{items.length ? <div className="kw-online-layout"><div className="kw-online-results">{items.map((item) => <button key={item.id} className={selected?.id === item.id ? "is-selected" : ""} onClick={() => { selectItem(item); }}><div><strong>{item.name}</strong><span>{item.category} · {item.version || "version UNKNOWN"}</span></div><p>{item.description || item.overview || "No description supplied."}</p><div className="kw-row-badges"><StatusBadge value={item.authority?.kind} /><StatusBadge value={item.availability} /><StatusBadge value={project ? item.projectCompatibility?.state || "UNKNOWN" : "NOT_EVALUATED"} /></div></button>)}</div>{operation && <div className="kw-operation-result" role="status"><pre>{JSON.stringify(operation, null, 2)}</pre></div>}</div> : <EmptyState title={view === "updates" ? "No verified update evidence" : `No ${viewLabel("online", view).toLowerCase()} evidence`} detail={view === "updates" ? "Updates require installedVersion, verifiedLatestVersion and version comparison." : "No verified source item matches this view."} />}</section>;
}

function OnlineContext({ project, control }: { project?: ProjectSummary; control: RecordRow | null }) {
  return <div className="kw-online-context"><div><Cloud size={17} /><strong>Online is global</strong><span>Opening this surface performs no remote catalog refresh.</span></div><div><span>Compatibility</span><StatusBadge value={project ? "PROJECT_CONTEXT" : "NOT_EVALUATED"} /><small>{project ? project.name : "No project selected"}</small></div><div><span>Control Center</span><StatusBadge value={control?.mode || "UNKNOWN"} /><small>{control ? "Policy evidence loaded" : "Loading policy evidence"}</small></div></div>;
}

export default OnlineSurface;
