import { useState, useEffect, useMemo, useRef, type ReactNode } from "react";
import type { SurfaceProps, RecordRow, TaskRow, ExecutionSnapshot, MarketplaceData, MarketplaceItem } from "./surfaceContracts";
import { fetchJson, fetchEvidence, jsonRequest, waitForTask } from "./api";
import { EmptyState, StatusBadge, EvidenceRows, EvidenceCards, TaskTable, EvidenceTable } from "./ui";
import { viewLabel } from "./navigation";

function ProjectsSurface({ view, workspace, project, onProjectSelect, onRefresh }: SurfaceProps) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<"activity" | "name" | "health">("activity"); const [selected, setSelected] = useState<string[]>([]);
  const [pathInput, setPathInput] = useState(""); const [remoteUrl, setRemoteUrl] = useState(""); const [targetName, setTargetName] = useState(""); const [message, setMessage] = useState("");
  const rows = useMemo(() => { let list = [...(workspace?.projects || [])]; if (view === "recent") list = list.filter((entry) => entry.categories.recent); if (view === "favorites") list = list.filter((entry) => entry.favorite); if (view === "pinned") list = list.filter((entry) => entry.pinned); if (view === "archive") list = list.filter((entry) => entry.archived); else list = list.filter((entry) => !entry.archived); list = list.filter((entry) => `${entry.name} ${entry.path} ${entry.projectType} ${entry.branch} ${entry.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())); list.sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "health" ? (b.healthScore ?? -1) - (a.healthScore ?? -1) : b.lastActivity.localeCompare(a.lastActivity)); return list; }, [workspace, view, query, sort]);
  if (view === "open-project") return <section className="kw-form-surface"><h2>Open Project</h2><p>Register an existing local directory without remote contact.</p><input aria-label="Local project path" value={pathInput} onChange={(e) => setPathInput(e.target.value)} /><button onClick={() => void fetchJson<{ project: ProjectSummary }>("/api/workspace/projects/open", jsonRequest({ path: pathInput.trim() })).then(async (data) => { onProjectSelect(data.project.id); await onRefresh(); setMessage(`Opened ${data.project.name}.`); }).catch((error) => setMessage(error instanceof Error ? error.message : "Open project failed."))}>Open project</button>{message && <p>{message}</p>}</section>;
  if (view === "import-project") return <section className="kw-form-surface"><h2>Import Repository</h2><p>Clone is policy-controlled and always requires explicit confirmation.</p><input aria-label="Repository HTTPS URL" value={remoteUrl} onChange={(e) => setRemoteUrl(e.target.value)} /><input aria-label="Destination folder" value={targetName} onChange={(e) => setTargetName(e.target.value)} /><button onClick={() => void (async () => { if (!window.confirm(`Clone ${remoteUrl}?`)) return; try { const data = await fetchJson<{ project: ProjectSummary }>("/api/workspace/projects/clone", jsonRequest({ remoteUrl, targetName, confirmed: true })); onProjectSelect(data.project.id); await onRefresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import failed."); } })()}>Clone with confirmation</button>{message && <p>{message}</p>}</section>;
  const allSelected = rows.length > 0 && rows.every((row) => selected.includes(row.id));
  return <section className="kw-projects"><div className="kw-table-toolbar"><label><Search size={14} /><input aria-label="Search local projects" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search projects, paths, types, branches…" /></label><select aria-label="Sort projects" value={sort} onChange={(e) => setSort(e.target.value as typeof sort)}><option value="activity">Last activity</option><option value="name">Project</option><option value="health">Health</option></select><label className="kw-select-all"><input type="checkbox" aria-label="Select all filtered projects" checked={allSelected} onChange={(e) => setSelected(e.target.checked ? rows.map((row) => row.id) : [])} />Select all</label><span>{rows.length} project(s)</span></div>{selected.length > 0 && <div className="kw-bulk-bar"><strong>{selected.length} selected</strong><button onClick={() => setSelected([])}>Clear selection</button></div>}{rows.length ? <div className="kw-table-wrap" aria-label="Projects engineering table"><table className="kw-table" data-testid="project-table"><thead><tr><th>Bulk</th><th>Project</th><th>Type</th><th>Branch</th><th>Trust</th><th>Git</th><th>Health</th><th>Last Activity</th></tr></thead><tbody>{rows.map((entry) => <tr key={entry.id} data-project-path={entry.path} data-project-id={entry.id} className={project?.id === entry.id ? "is-selected" : ""}><td><input type="checkbox" aria-label={`Select ${entry.name} for bulk actions`} checked={selected.includes(entry.id)} onChange={(e) => setSelected((current) => e.target.checked ? [...new Set([...current, entry.id])] : current.filter((id) => id !== entry.id))} /></td><td><button className="kw-project-select" aria-label={`Select project ${entry.name}`} onClick={() => onProjectSelect(entry.id)}><strong>{entry.name}</strong><small>{entry.path}</small>{entry.tags.length ? <small>{entry.tags.join(" · ")}</small> : null}</button></td><td>{entry.projectType}</td><td><code>{entry.branch}</code></td><td><StatusBadge value={entry.trust} /></td><td><span>{entry.modifiedFiles + entry.untrackedFiles} changed</span><small>{entry.ahead} ahead · {entry.behind} behind</small></td><td>{entry.healthScore ?? "NOT_SCANNED"}</td><td>{new Date(entry.lastActivity).toLocaleString()}</td></tr>)}</tbody></table></div> : <EmptyState title={view === "pinned" ? "No pinned projects" : "No projects found"} detail="Open or import a project to populate this engineering table." />}</section>;
}

export default ProjectsSurface;
