import { useState, useEffect } from "react";
import { ShieldCheck } from "lucide-react";
import type { SurfaceProps, RecordRow } from "./surfaceContracts";
import type { KForgePlatformSettings, KForgeActivity, KForgeOnlineView, WorkspaceResponse, ProjectSummary } from "@shared/workspace";
import { fetchJson, fetchEvidence, jsonRequest } from "./api";
import { EmptyState, StatusBadge, EvidenceRows } from "./ui";
import { viewLabel, ACTIVITIES, activityDefinition } from "./navigation";
import { SimpleFetchSurface } from "./surfaceShared";

function SystemSurface(props: SurfaceProps) {
  const { view, project, workspace, settings, onSettings, onRefresh } = props;
  if (view === "settings") return settings ? <SettingsSurface settings={settings} onSettings={onSettings} /> : <p className="kw-message">Settings unavailable.</p>;
  if (view === "self-audit") return project ? <SelfAudit project={project} /> : <EmptyState title="No project selected" detail="Self Audit is project scoped." />;
  if (view === "system-diagnostics") return <SystemDiagnostics />;
  if (view === "trust") return project ? <section className="kw-action-surface"><h2>{project.name}</h2><StatusBadge value={project.trust} /><p>Trust enables local process and write-capable operations, not remote writes.</p>{project.trust !== "trusted" && <button onClick={() => void (async () => { if (!window.confirm(`Trust ${project.name}?`)) return; await fetchJson(`/api/workspace/projects/${encodeURIComponent(project.id)}/trust`, jsonRequest({ confirmed: true })); await onRefresh(); })()}>Trust project with confirmation</button>}</section> : <EmptyState title="No project selected" detail="Trust is contextual." />;
  if (view === "online-offline") return <section className="kw-surface-section"><h2>Operating policy</h2><EvidenceRows value={workspace?.localPlatform as unknown as RecordRow} /><p>Remote metadata and transfers remain policy-controlled; Offline mode does not silently contact providers.</p></section>;
  if (!project) return <EmptyState title="No project selected" detail={`${viewLabel("system", view)} needs project context.`} />;
  return <SimpleFetchSurface url={view === "permissions" ? `/api/workspace/projects/${encodeURIComponent(project.id)}/agent/tools` : view === "storage" ? `/api/workspace/projects/${encodeURIComponent(project.id)}/cache` : "/api/workspace/platform"} title={viewLabel("system", view)} />;
}

function SettingsSurface({ settings, onSettings }: { settings: KForgePlatformSettings; onSettings: (settings: KForgePlatformSettings) => void }) {
  const [draft, setDraft] = useState(settings); const [message, setMessage] = useState(""); useEffect(() => setDraft(settings), [settings]);
  const save = async () => { try { const data = await fetchJson<{ settings: KForgePlatformSettings }>("/api/workspace/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ version: 3, general: { startupActivity: draft.general.startupActivity, startupOnlineView: draft.general.startupOnlineView }, appearance: draft.appearance, preview: draft.preview, privacy: { remoteContextPolicy: draft.privacy.remoteContextPolicy }, git: {} }) }); onSettings(data.settings); setDraft(data.settings); setMessage("Settings v3 saved locally."); } catch (error) { setMessage(error instanceof Error ? error.message : "Settings save failed."); } };
  return <section className="kw-settings"><h2>Settings v3</h2><div className="kw-settings-grid"><label>Startup activity<select aria-label="Startup activity" value={draft.general.startupActivity} onChange={(e) => setDraft({ ...draft, general: { ...draft.general, startupActivity: e.target.value as KForgeActivity } })}>{ACTIVITIES.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select></label><label>Startup Online view<select aria-label="Startup Online view" value={draft.general.startupOnlineView} onChange={(e) => setDraft({ ...draft, general: { ...draft.general, startupOnlineView: e.target.value as KForgeOnlineView } })}>{activityDefinition("online").views.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select></label><label>Theme<select aria-label="Theme" value={draft.appearance.theme} onChange={(e) => setDraft({ ...draft, appearance: { ...draft.appearance, theme: e.target.value as "light" | "dark" | "system" } })}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Information density<select aria-label="Information density" value={draft.appearance.density} onChange={(e) => setDraft({ ...draft, appearance: { ...draft.appearance, density: e.target.value as "compact" | "comfortable" } })}><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select></label><label className="kw-checkbox"><input aria-label="Reduce motion" type="checkbox" checked={draft.appearance.reducedMotion} onChange={(e) => setDraft({ ...draft, appearance: { ...draft.appearance, reducedMotion: e.target.checked } })} />Reduce motion</label><label>Remote context policy<select aria-label="Remote context policy" value={draft.privacy.remoteContextPolicy} onChange={(e) => setDraft({ ...draft, privacy: { ...draft.privacy, remoteContextPolicy: e.target.value as "blocked" | "ask" } })}><option value="ask">Ask</option><option value="blocked">Blocked</option></select></label></div><div className="kw-security-invariants"><ShieldCheck size={18} /><div><strong>Enforced invariants</strong><span>secretRedaction = true · confirmRemoteWrites = true · Git mutation remains confirmation-gated</span></div></div><button onClick={() => void save()}>Save settings</button>{message && <p className="kw-message" role="status">{message}</p>}</section>;
}

function SelfAudit({ project }: { project: ProjectSummary }) {
  const [data, setData] = useState<RecordRow | null>(null); const [message, setMessage] = useState("No persisted Self Audit evidence loaded.");
  const read = async () => { const response = await fetchEvidence(`/api/workspace/projects/${encodeURIComponent(project.id)}/self-audit`); if (response.ok) { setData((response.data.selfAudit || response.data) as RecordRow); setMessage(""); } };
  useEffect(() => { void read(); }, [project.id]);
  const run = async () => { setMessage("Running observational KForge Self Audit…"); const response = await fetchEvidence(`/api/workspace/projects/${encodeURIComponent(project.id)}/self-audit`, { method: "POST" }); if (response.ok) { setData((response.data.selfAudit || response.data) as RecordRow); setMessage("Self Audit evidence persisted. Persistence/restart boundary remains explicit."); } else setMessage(String(response.data.error || "Self Audit failed.")); };
  return <section className="kw-self-audit kw-surface-section"><h2>KForge Self Audit</h2><p>This is observational: it never applies a fix, starts Preview, or contacts a remote provider implicitly. Source mutation is NONE.</p><button onClick={() => void run()}>Run KForge Self Audit</button>{message && <p className="kw-message" role="status">{message}</p>}{data && <><EvidenceRows value={data} /><pre>{JSON.stringify(data, null, 2)}</pre></>}</section>;
}

function SystemDiagnostics() {
  const [rows, setRows] = useState<RecordRow[]>([]); const [message, setMessage] = useState("Loading measured diagnostics…");
  const refresh = async () => { try { const [workspace, platform, providers, models] = await Promise.all([fetchJson<WorkspaceResponse>("/api/workspace/projects"), fetchJson<RecordRow>("/api/workspace/platform"), fetchJson<{ providers: RecordRow[] }>("/api/workspace/ai/providers"), fetchJson<RecordRow>("/api/workspace/ai/models")]); const modelProviders = (models.providers as RecordRow[] || []); setRows([{ id: "projects", name: "Projects & repositories", state: workspace.projects.length ? "AVAILABLE" : "NOT_CONFIGURED", count: workspace.projects.length }, { id: "search", name: "Search & file inspection", state: "AVAILABLE", source: "Registered bounded local adapters" }, { id: "commands", name: "Tests, build & terminal", state: "EVIDENCE_DEPENDENT", source: "Project action descriptors" }, { id: "platform", name: "Local platform", ...platform }, ...providers.providers, ...modelProviders, { id: "models", name: "Local models", state: String((models.ollama as RecordRow | undefined)?.serviceReachable ? "REACHABLE" : "NOT_DETECTED"), source: "Local provider inventory" }]); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Diagnostics unavailable."); } };
  useEffect(() => { void refresh(); }, []);
  return <section className="kw-surface-section"><div className="kw-toolbar"><h2>System Diagnostics</h2><button onClick={() => void refresh()}>Refresh diagnostics</button></div><p>Missing tools remain UNAVAILABLE / NOT_DETECTED rather than being represented as successful.</p>{message && <p className="kw-message">{message}</p>}<div className="kw-system-grid">{rows.map((row, index) => <article key={String(row.id || row.name || index)}><strong>{String(row.name || row.label || row.id || `Capability ${index + 1}`)}</strong><EvidenceRows value={row} /><details><summary>Diagnostic evidence</summary><pre>{JSON.stringify(row, null, 2)}</pre></details></article>)}</div></section>;
}

export default SystemSurface;
